[project]
name = "99bottles-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "pytest-watcher>=0.6.3",
    "ruff>=0.14.11",
]
